
server:  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/auemura/config/
          search-paths: fornecedor, loja, transportador